### ISSUE TITLE
Where can I get mode-line-color?

### ISSUE THREAD

**Issue by tarsius** [tarao/evil-plugins#8]
I cannot find the package `mode-line-color` anywhere. It is required by `evil-mode-line`.

(Note to self: add both packages to the Emacsmirror.)

**Comment by tarao** [comment]
It is in https://github.com/tarao/elisp repository as the README says. Or you mean you want some managed package in ELPA?

**Comment by tarsius** [comment]
Ah sorry, I should have noticed that. In my defense, I am currently investigating missing dependencies for a few hundred packages on the Emacsmirror :-)

I'll get back to you later with a request to split-up `elisp` into multiple repositories (and maybe `evil-plugins` too).
